name: PostgreSQL service example
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # latest

      - name: Install Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # latest
        with:
          go-version: 1.17

      - name: Go Test
        run: go test -v -race -shuffle=on -coverprofile=coverage.txt ./...
